### ISSUE TITLE
Fiddler has error and my game not start

### ISSUE THREAD

**Issue by WorldBear** [denikson/CM3D2.MaidFiddler#10]
![image](https://cloud.githubusercontent.com/assets/21049092/17685443/c63bfee2-639e-11e6-84da-4b9cb9f250f9.png)
![image](https://cloud.githubusercontent.com/assets/21049092/17685445/d15bedaa-639e-11e6-9773-d141a55a20ce.png)
![image](https://cloud.githubusercontent.com/assets/21049092/17685448/d47cab00-639e-11e6-990a-a66294b6f3bf.png)
How can i fix it?
And I'm not good at English cause I'm korean. sorry :(

**Comment by ghorsington** [comment]
Hello,  WorldBear! 

This seems to be the same problem as in #3. 
Update your version of CM3D2 and try to run the game again. 

If the problem is still there, create a new issue.
