### ISSUE TITLE
Game crashes on start up after updating to ver.1.39

### ISSUE THREAD

**Issue by zetsuei380** [denikson/CM3D2.MaidFiddler#18]
After updating to 1.39, for some reason the game keeps crashing on the logo when you open the game. I don't know if its because of maid fiddler, but it started working after I uninstalled maid fiddler.

**Comment by ghorsington** [comment]
The tool seems to work fine on 1.39 on my end. Make sure you have installed the tool properly.

If you encounter any problems, make sure to include an error log (or a detailed description of the error) before creating an issue. That way the problem can actually be fixed.
