### ISSUE TITLE
Nothing seems to be working

### ISSUE THREAD

**Issue by OrsoRosso** [denikson/CM3D2.MaidFiddler#19]
I've done everything the guide told me to do, and at first it showed an error(i'll link down).. then i updated my game from 1.32 to 1.39.. nothing seems to be working.. save files are still there so no problem, but it doesn't load any message and the debug window doesn't show up either.. it's likely i've messed up something during the update but could please someone tell me how to make this work?
Thanks.
![assemblyerror](https://cloud.githubusercontent.com/assets/22712619/19214973/52458b8a-8d91-11e6-81a0-8e040877d2d6.png)

**Comment by ghorsington** [comment]
Seems like you haven't patched your Assembly-CSharp.dll after updating the game, which is why UnityInjector (and plugins) are not loaded. 
Run ReiPatcher (or use Sybaris) to patch the assembly.

**Comment by OrsoRosso** [comment]
Done already, now it doesn't show that error message anymore but it won't load the fiddler aswell.. and the games is back in japanese.. i can't even see the window in which is shown if the fiddler is installed or not..
p.s. before updating, running ReiPatcher didn't solve anything

**Comment by ghorsington** [comment]
Run ReiPatcher and observe the output. Possibly some patcher is causing an error.

Refer to the [ReiPatcher usage guide](http://umaiumeunion.github.io/guides_reipatcher/05_using_patcher) if you are unsure about how to use it.
