### ISSUE TITLE
Method not found: 'MaidParam.StatusAccess.get_is_marriage'

### ISSUE THREAD

**Issue by AmaterasuOomikami** [denikson/CM3D2.MaidFiddler#20]
After patching and after loading a game, as I first click a maid profile in order to load her info :
![Oh noes](https://cloud.githubusercontent.com/assets/22856648/19414043/60d38b10-9341-11e6-8a4d-8de351f38ca3.png)

Associated log :
[MaidFiddler_err_Fl0cd2T10wg=.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/531499/MaidFiddler_err_Fl0cd2T10wg.txt)

**Comment by ghorsington** [comment]
This is a bug that still persists in the current version of Maid Fiddler.
This issue will be (hopefully) fixed in the next version.

However, you can fix it yourself by **updating the game version** to 1.39.

**Comment by AmaterasuOomikami** [comment]
Thanks a lot for answering. Good luck, and have a nice day !
