### ISSUE TITLE
Broken interface

### ISSUE THREAD

**Issue by Thf772** [denikson/CM3D2.MaidFiddler#21]
When I open Maid Fiddler by pressing A, this is what I get:
![cm3d2_mf_1](https://cloud.githubusercontent.com/assets/18517127/19418222/f2134290-93bf-11e6-97c3-3fd5ed24e715.png)

After clicking on a maid (the rental maid at the top), part of the interface appears but it does not do anything:
![cm3d2_mf_2](https://cloud.githubusercontent.com/assets/18517127/19418304/842ae1be-93c1-11e6-8d27-eb9d5907679a.png)

It happens everytime I open MaidFIddler, both right after loading the game or after playing for a while.
I use a save on which I already used another version of the Fiddler, but this problem also happens on a new game. _This problem happens with both 0.11.1 and 0.11_

I use the latest game version (139), x64, with all DLC (at least the ones in the Pastebin), and Cecil.Inject 1.2.3. Reinstalling and repatching didn't solve the problem.

**Comment by ghorsington** [comment]
What operating system are you running? Also, are you running your game in fullscreen?
If that is the case, have you tried to run it in windowed mode?

**Comment by Thf772** [comment]
I'm on Windows 10 Pro, and I run the game in a maximized window. I always used this setup before, and I had no problem.

**Comment by ghorsington** [comment]
It might be some OS/computer-related graphic artifact, in which case there is currently nothing I can do given the way Maid Fiddler is working (as stated in the [FAQ](https://github.com/denikson/CM3D2.MaidFiddler/wiki/FAQ#q-why-does-the-gui-have-randomly-disappearing-scroll-bars-and-other-visual-artifacts) as well).
I am currently planning to move Maid Fiddler to a separate Windows executable, which should fix these kind of issues. However, the implementation will not be available soon.

What about the GPU dirvers? Have they been updated recently? It might be that the update/lack thereof contributed to the issue.

...or you could just try something basic, like Alt-Tabbing out and back in.

**Comment by Thf772** [comment]
GPU drivers are up to date, I have a GeForce 950M and I have this problem with both "integrated graphics" and the GeForce.
BTW I have GeForce Experience installed as well as Game-Ready Driver. Maybe that's the problem.

**Comment by ghorsington** [comment]
It might be the possibility. Have you tried setting `OpenOnStartup` to true in MaidFiddler.ini?
If the issue still persists, it _could_ be due to the graphics driver.

I'll try updating my GPU drivers (currently working on a laptop with 840M).
**EDIT**: Still works fine here

**Comment by Thf772** [comment]
Enabling `OpenOnStartup` did not work, but the result was different: the MaidFiddler window was completely white, and there was only the outline of the text fields ans frames.

I'll try re-installing the graphic drivers, without GeForce Experience this time.

**Comment by ghorsington** [comment]
While you're at it, try the following debug version of Maid Fiddler:

[CM3D2.MaidFiddler.Plugin.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/531968/CM3D2.MaidFiddler.Plugin.zip)

Make sure `OpenOnStartup` is set to true, so that Maid Fiddler will not change the opacity of its own window.

**Comment by Thf772** [comment]
Tested it after uninstalling the driver, before reinstalling: everything worked.
[test-noDriver.log.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/532007/test-noDriver.log.txt)

Tested again after reinstalling the driver (373.06) without GeForce Experience: worked as well.
[test-withDriver.log.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/532008/test-withDriver.log.txt)

Maybe I'll try reinstalling GeForce Experience someday too but I've never found it actually useful.

Anyway, thanks for your help!
