### ISSUE TITLE
MaidFiddler crash when using MAX_YOTOGI_LVL

### ISSUE THREAD

**Issue by z598523287** [denikson/CM3D2.MaidFiddler#22]
Game ver. 1.39  MaidFiddler Ver.0.11 and 0.11.1

**Comment by ghorsington** [comment]
Does the tool just close? Or is there any error message along with the error log?
What about the debug console?

**Comment by z598523287** [comment]
Just close.
MaidFiddler can reopen

**Comment by ghorsington** [comment]
Try using the debug build of the plugin:

[CM3D2.MaidFiddler.Plugin.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/531934/CM3D2.MaidFiddler.Plugin.zip)

Now it _should_ create an error log when crashing.

**Comment by z598523287** [comment]
=== Maid Fiddler DUMP ===

Game version: 139
Mod version: BETA 0.11.1
Info: Failed to set all yotogi levels to max
Error message: System.InvalidProgramException: Invalid IL code in MaidParam:AddSkillExp (int,int): IL_006c: ret       

  at CM3D2.MaidFiddler.Plugin.Gui.MaidFiddlerGUI.<SetMaxYotogiLevel>b__27_0 () [0x00000] in <filename unknown>:0 
  at CM3D2.MaidFiddler.Plugin.Utils.Debugger.Assert (System.Action action, System.String errMsg) [0x00000] in <filename unknown>:0 

![image](https://cloud.githubusercontent.com/assets/22060478/19418924/8e9ae8d0-9400-11e6-8b23-b0ef21325191.png)

**Comment by ghorsington** [comment]
Make sure you have the **latest** version of Cecil.Inject, and perform a **full** re-patch from a fresh Assembly-CSharp.dll.

This is the same issue as #4.
