### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by divinefinder** [denikson/CM3D2.MaidFiddler#23]
Ver. 1.39 
Using Mods (But they work with the game just fine). After applying the MaidFiddler files, and running it, it produces "game crash" box. Game can still be played if you dont press the "ok" button but in some areas during the gameplay, it causes the game to freeze and crash.

**Comment by ghorsington** [comment]
Whether it is the Unity's "The game has crashed" or Maid Fiddler's "Oh noes" window, it should have created a crash log to the CM3D2 folder. Could you provide the crash logs (as a zip, for example). 

Either that, or an exact error message could help.

**Comment by Muens** [comment]
https://i.gyazo.com/2cfe1648803c2fa619c19dddedfaaea4.png
[output_log.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/547120/output_log.txt)
http://image.prntscr.com/image/ce0c3a09556743f0b2fcf5419f45bc4c.png
This is all I get when I try to play and use MF. As divinefinder stated above you can still play the game as long as you dont press okay on the crash window but you cannot use the MF. I have read the FAQ countless times, installed fresh patches countless times, followed every direction and made sure my files were in the correct areas countless times. It really is a no brainer especially with the step by step guide but for whatever god known reason it still will not work for me. If you want me to grab any other information I'd be happy to do that as well. Also I apologize if this is the wrong place to post.

**Comment by divinefinder** [comment]
[Cm3d2 Error Crash.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/549331/Cm3d2.Error.Crash.zip)

Hopefully this will help. I have restored my game by reapplying the 131 HF Patch with clean installs of ReiPatcher and Unity. Sorry for the delayed response. 

Edit: I would like to add on, the image (from Gyazo) that Muens has provided is exactly what I get as the "game crash" box that I have mentioned.

**Comment by doublear** [comment]
I just want to say that i also experiencing same issue as well

**Comment by zetsuei380** [comment]
still crashing the game even after updating to 1.40

**Comment by YohanDevelter** [comment]
Might be linked to Windows 10 anniversary. I had no problems before the update, and as soon as I did it this issue happened, with Sybaris anyway, when I tried to use the ReiPatcher version, ReiPatcher just denied because of some missing library (I didn't took a screenshot and since I'm another PC I can't replicate it). I have another PC on Windows 7 and have no problem with the extension, even if it's litteraly a copy and paste of the installation I have on my Windows 10 PC

These are the output files of the crash :  
[Crash.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/560056/Crash.zip)

**Comment by ghorsington** [comment]
Sorry for the _long_ response delay. I had some other problems to attend to, but now here's what I know about this issue, and what is being done towards fixing it.

This is a known issue (as documented in #11 and indirectly in the [FAQ](https://github.com/denikson/CM3D2.MaidFiddler/wiki/FAQ#q-why-does-the-gui-have-randomly-disappearing-scroll-bars-and-other-visual-artifacts)). 
As of right now there is no clear solution given how Maid Fiddler's GUI is implemented. 
_However_, I am working on rewriting Maid Fiddler to separate the GUI from the plugin, which **will** ultimately fix this and many other problems. Unfortunately, considering my current schedule, I cannot provide an ETA of this "final release" update.

All I can say right now is to try the "solution" provided in #11 and wait for the final rewrite of Maid Fiddler. Those that know a bit more about GitHub may have noticed the [wpf](https://github.com/denikson/CM3D2.MaidFiddler/tree/wpf) branch in the repository, which contains the upcomming release version of Maid Fiddler. You can try it out from time to time, but it will take me some time until the branch will contain a fully functioning version of the new Maid Fiddler.

Thank you all for the feedback on the issue. I'll close this one for now, but don't hesitate to send in more issues (even the similar ones), should they occur. I will try to answer/fix them as fast as I can.
