### ISSUE TITLE
Feature enum parse error..? Locks up game.

### ISSUE THREAD

**Issue by DatumX** [denikson/CM3D2.MaidFiddler#24]
Updated to latest "Mono.Cecil.Inject", and updated to latest version of Maid Fiddler. ReiPatcher patched it correctly with no errors, but whenever I get on the KISS logo screeen on startup, Maid Fiddler encounters an error and spits out a log attached below. On the CAUTION screen it seems to sit there fine until I click. Then I get a popup box that says "(0) Feature enum parse error." The CMD box pops up two lines:

"\Assert ! Feature enum parse error.
Exception: Feature enum parse error."

Trying to load to the main screen spits out more text in the CMD box:

"ArgumentNullException: Argument cannot be null.
Parameter name: s"

Fiddler error file attached below.

[MaidFiddler_err_y1Zom0kG1Ag=.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/573645/MaidFiddler_err_y1Zom0kG1Ag.txt) 

EDIT: Would also like to say this all started when I tried to update cecil.inject alongside Maid Fiddler after receiving the issue in the following link: https://github.com/denikson/CM3D2.MaidFiddler/issues/4

Was running latest version before v1.40 which I have yet to install. Might try installing v1.40 of CM3D2 and see if it helps any.

EDIT 2: It appears as though updating to v1.40 somehow fixed it even though it came out literally either today or yesterday by my watch. o.O

**Comment by ghorsington** [comment]
Judging by the error, the issue wasn't really related to Maid Fiddler.
For reference, if you look at the line of the code [where the issue most likely occurred](https://github.com/denikson/CM3D2.MaidFiddler/blob/a7b46b95a19a8261bdf05a4156f3de13d7a748ac/CM3D2.MaidFiddler.Plugin/Gui/MaidFiddlerGUI.Work.cs#L35), Maid Fiddler only iterates through the noon work data without editing it. That means the game would still crash even without Maid Fiddler installed. Moreover, Maid Fiddler does work fine with CM3D2 v. 1.39 and older (I still have an old version installed).

The easiest solution would be to install the latest version of the game (exactly what you did) or reinstalling the old version and making sure you have all the files for the game.
