### ISSUE TITLE
Maid Fiddler isn't even appearing in CMD menu

### ISSUE THREAD

**Issue by theamdrag** [denikson/CM3D2.MaidFiddler#25]
So, when starting to get Maid Fiddler, I got Cecil.Inject and put it in the Reipatcher folder with Mono.Cecil there. Then I downloaded Maid Fiddler, and put everything in the appropriate places in my Sybaris folders, although I had to create a "Managed" folder in the Plugins folder, as one did not exist yet. Tried firing up the game, and Maid Fiddler wasn't even listed or mentioned in the CMD window.

I ended up finding a copy of Mono.Cecil in the Sybaris/Loader folder, deleted the old Maid Fiddler stuff in Sybaris, put a copy of Cecil.Inject in the Loader folder, and then put in new the Maid Fiddler files into their folders again. Fired up the game, still nothing. Deleted the copy of Cecil.Inject from the Reipatcher folder, tried firing up the game, no dice. I have no clue why the game/CMD window isn't even acknowledging Maid Fiddler.

For reference, I have Reipatcher from the HF patch, Sybaris version 160212, and Cecil.Inject 1.2.3, so everything should be good to go there... Do I still need to do the Assembly.CSharp thing and all even after putting the stuff into Sybaris? I seriously have no idea what's going on...

**Comment by ghorsington** [comment]
Hello and sorry for a *loooooong* response time. 
Nevertheless, consider reading the [installation guide for Sybaris](https://github.com/denikson/CM3D2.MaidFiddler/wiki/Installation-and-basic-usage#installation-sybaris). If you use a ReiPatcher + Sybaris combination, consider performing a **full re-patch** (restoring Assembly-CSharp.dll and re-patching it). Make sure that you use *either* Sybaris *or* ReiPatcher version of Maid Fiddler.

If you (still) have further questions, open a new ticket.
