### ISSUE TITLE
Cannot Run

### ISSUE THREAD

**Issue by mysoundmagic** [denikson/CM3D2.MaidFiddler#26]
hello, i have followed the readme but still cannot run the application

in cmd i got this error 

```
Error in Patcher 'MaidFiddler Patcher'
  Resource 'ReiPatcher.DLL.Mono.Cecil.Inject.dll' not Found
```

how to solve this ? use ReiPatcher

**Comment by woulez** [comment]
You need to put the file 'ReiPatcher.DLL.Mono.Cecil.Inject.dll' into "\<cm3d2 installation root>\ReiPatcher\"-folder.
As for where you can actually find the file I cannot help you, sorry.

**Comment by ghorsington** [comment]
Oh my! Sorry not noticing this issue: unfortunately I haven't been able to work on and monitor this project lately! 

Nevertheless, as @woulez pointed out (and in case you still haven't found the solution), you need Mono.Cecil.Inject -- it's one of the requirements for Maid Fiddler as stated in the [installation guide](https://github.com/denikson/CM3D2.MaidFiddler/wiki/Installation-and-basic-usage#requirements). You can download Cecil.Inject from [here](https://github.com/denikson/Mono.Cecil.Inject/releases).  

You'll want to put the DLL in the same folder where ReiPatcher.exe resides.

**Comment by mysoundmagic** [comment]
ok thank you guys
