### ISSUE TITLE
 do not use in  x86 sybaris 

### ISSUE THREAD

**Issue by holy1017** [denikson/CM3D2.MaidFiddler#28]
not use in x86 sybaris

**Comment by ghorsington** [comment]
Ok... Could you elaborate a teeny bit? Does it not patch? Something else?

**Comment by ghorsington** [comment]
Oh my! It's been about two weeks since the issue was posted. 

I'm closing this until you'll provide more information. Seems to work fine on both x84/64-bit versions of CM3D2 1.52.

If you still have problems, please re-open the issue with a more exact description of the problem.
