### ISSUE TITLE
Crashing after installing Vigil 06

### ISSUE THREAD

**Issue by Nixonator** [denikson/CM3D2.MaidFiddler#3]
=== Maid Fiddler DUMP ===

Game version: 127
Mod version: BETA 0.9b
Info: Failed to update player values
Error message: System.NullReferenceException: Object reference not set to an instance of an object
  at CM3D2.MaidFiddler.Plugin.Gui.MaidFiddlerGUI+PlayerInfo.UpdateDays () [0x00000] in <filename unknown>:0 
  at CM3D2.MaidFiddler.Plugin.Gui.MaidFiddlerGUI+PlayerInfo.UpdateAll () [0x00000] in <filename unknown>:0 

Game worked fine before, I downloaded and sued the updater for Vigil skills 06, now error. I ahve played around with and searched for a few hours now (usually I can find a way to fix things, but this one has me beaten)

Tried to re-install maid fidler, tried to re-install the vigil pack, tried to re-install C-sharp assembly. Each time reipatcher showed no errors and everything was a success

Game works fine after deleting the files vigil 06 added.
Still breaks when using the vigil 06 files.

Halp?

**Comment by ghorsington** [comment]
> I downloaded and sued the updater for Vigil skills 06

Which additional content do you mean by "Vigil Skills 06"? If it is the _Yotogi Class Skills Vol.6_, it requires CM3D2 version 1.31 or later to work.

In addition, when does the error occur? Everything seems to work fine on my end.

In any case, consider updating CM3D2 to the latest version (according to the error dump you have version 1.27 installed).

If the error still persists even after updating CM3D2, either reopen this issue or open a more detailed one.
