### ISSUE TITLE
Bug with night service values

### ISSUE THREAD

**Issue by wrthmnxv** [denikson/CM3D2.MaidFiddler#30]
When i lock the current mind and reason when doing night service, the excitement bar would go over 300, any interaction will give her excitement even with ejaculating and after i reset the excitement bar to 0, it would go backwards to minus range when i do any interaction. Current game ver. 1.51. Thanks for your hardwork!!

**Comment by ghorsington** [comment]
Greetings!

Do you perhaps mean that when locking those values you mentioned **any** interaction would rise the excitement (even the ones that aren't supposed to)?

I attempted to reproduce the issue on CM3D2 1.52, and it worked fine. I suspect that some other plug-in that edits values related to night service might interfere.

I suggest you try disabling all plug-ins except Maid Fiddler and attempt to see if the issue disappears.
If I recall correctly, AddYotogiSlider plug-in is one of those that can edit night service values too and thus can interfere with Maid Fiddler's approach to edit the values. However, in AddYotogiSlider you can disable the value editing through its own GUI.

Do you have AddYotogiSlider or any other plug-ins that are made to edits the aspects of night service? If so, attempt to disable them first.

**Comment by wrthmnxv** [comment]
Hi,
I've tried to run maidfiddler 0.11.2 with and without other plugins today, and fortunately the bugs doesn't occur anymore.., so it might be the sybaris / maidfiddler instability. Anyways thanks for the fast response, and have a good day!!

**Comment by ghorsington** [comment]
Glad to hear it works. However, again, I highly doubt the problem is with Maid Fiddler, as I did test your issue on both Sybaris and ReiPatcher versions. I still think there might be some other plug-in interfering.

Nevertheless, do not hesitate to tell if you have found the culprit or there is any other kind of issue.
