### ISSUE TITLE
Game Crash When Launch The Game

### ISSUE THREAD

**Issue by rymesaint** [denikson/CM3D2.MaidFiddler#31]
Please fix this bug, i want to play the game but as soon i click the launcher and waiting for the plugin to load. the game crash because of the plugin. I'm using windows 10 Build 15063 64bit. How i know? because after i rename the plugin it will run normally.
I attach the crash log here.

[output_log.txt](https://github.com/denikson/CM3D2.MaidFiddler/files/1254895/output_log.txt)

[error.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/1254897/error.zip)

**Comment by ghorsington** [comment]
Greetings!

Thank you for informing the version of your operating system. However, what is more important to me are the versions of **CM3D2**, **Maid Fiddler** and **Cecil.Inject**. Could you provide those as well? In addition, what locale emulator (or locale changing technique) are you using?

Looking at the output log, the error does not seem to come from within Maid Fiddler itself.
Indeed, as the stack trace claims (*posting this mainly for technical and future reasons*):
```
0x0000000005E9769A (Mono JIT Code) (wrapper managed-to-native) object:wrapper_native_00007FF934D4A850 (DLLFileSystem/Data&,string)
0x0000000005ED9D32 (Mono JIT Code) FileSystemArchive:IsExistentFile (string)
0x0000000005F2024B (Mono JIT Code) wf:ReadEnabledIdListCsv (string,System.Collections.Generic.HashSet`1<int>&)
0x000000003637307E (Mono JIT Code) Schedule.ScheduleCSVData:CVSRead ()
0x0000000036372AB7 (Mono JIT Code) Schedule.ScheduleCSVData:.cctor ()
0x00000000077A0E13 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
```

That is, the game crashes when it attempts to load some schedule-related data.
Given the amount of plug-ins you have (at least stated by the output log) and the memory capacity of your computer (3.5 GB RAM and 1.3 GB VRAM, as stated in `output_log.txt` and `error.log`), I would suspect some sort of memory insufficiency.

To rule out (or confirm) the above-mentioned, please do the following:

1. Remove all (or majority of) plug-ins except Maid Fiddler. You can do that by moving them all to some other folder temporarily. 
2. Do the same for patchers as well (located in Sybaris' `Loader` folder). Make sure to leave those assemblies that are not patchers (for instance `Mono.Cecil`, `Sybaris.Loader`, etc).
3. Try to run the game with (possibly) only Maid Fiddler.

If the crash still happens, please send the crash log.

**Comment by ghorsington** [comment]
Closing the issue for the lack of response. I have tried to replicate the issue numerously, but to no avail.

If you happen to experience the same issue again, please reopen the issue with more information provided.
The added issue template should help with creating the proper description of the issue.
