### ISSUE TITLE
Invalid Program Exception: Invalid IL code in MaidParam:AddSkillExp?

### ISSUE THREAD

**Issue by Algester** [denikson/CM3D2.MaidFiddler#4]
I know this is still premature for me to say but this is only visible with the game running on V1.31.2
![invalidprogram exception](https://cloud.githubusercontent.com/assets/6236070/15998618/4c8a0bb0-3172-11e6-9fe7-1453a3ba771f.JPG)
I have attached the log if your interested

**Comment by ghorsington** [comment]
Make sure you have the latest version of [Cecil.Inject](https://github.com/denikson/Mono.Cecil.Inject/releases) installed. If Maid Fiddler Patcher is used with Cecil.Inject 1.1 or older, `MaidParam.AddSkillExp` is patched wrongly.

**In summary:** Update Cecil.Inject, restore Assembly-CSharp.dll to an unpatched one and run ReiPatcher again. Try to do that, and tell if it helped.
