### ISSUE TITLE
Crash after installing class skill #7

### ISSUE THREAD

**Issue by soknife** [denikson/CM3D2.MaidFiddler#6]
i've updated to 1.31.2, applied hf patch v1.0.131.0, installed cecil 1.2.3, installed maid fiddler 0.9c, and get this error on launch. the error goes away as soon as i remove all class skill #7 files in gamedata

=== Maid Fiddler DUMP ===

Game version: 131
Mod version: BETA 0.9c
Info: Failed to update player values
Error message: System.NullReferenceException: Object reference not set to an instance of an object
  at CM3D2.MaidFiddler.Plugin.Gui.MaidFiddlerGUI+PlayerInfo.UpdateDays () [0x00000] in <filename unknown>:0 
  at CM3D2.MaidFiddler.Plugin.Gui.MaidFiddlerGUI+PlayerInfo.UpdateAll () [0x00000] in <filename unknown>:0

**Comment by ghorsington** [comment]
Possibly the same as #3, which means the issue might be buried somewhere in the initialisation code.

Will look into this as soon as possible.

**Comment by ghorsington** [comment]
Same issue as #3, update your version of CM3D2 before installing any new skill packs.

For more information, refer to the [FAQ](https://github.com/denikson/CM3D2.MaidFiddler/wiki/FAQ#q-i-installed-instert-dlc-name-here-and-now-maid-fiddler-crashes-every-time-i-launch-the-game-whats-the-problem).
