### ISSUE TITLE
"Open translation folder" button does not work on Sybaris

### ISSUE THREAD

**Issue by CaiMiao** [denikson/CM3D2.MaidFiddler#8]
> Background:
> I'm using Chinese translation patch which only supports ReiPatcher.
> As the main trend in Chinese community we combined Sybaris + ReiPatcher to make translation to work,
> 
> <del>which means we use both Sy. & Rei. to make this plugin to work.</del>

Also "Open translation folder" option is not working.

**Comment by ghorsington** [comment]
Did you manage to replicate the black screen issue? 
If yes, have you tried to:
1. Disable Maid Fiddler and see if the same problem persists, and
2. Observe the UnityInjector's Debug console and see if there are any errors before the black screen?

While using Sybaris + ReiPatcher combination with Maid Fiddler works, make sure you have only one of the patchers active at the time.

As for the "Open translation folder" button, which locale emulator are you using (if any)?
In addition, does pressing the button cause any error messages?

**Comment by CaiMiao** [comment]
> which means we use Sybaris necessaries + Rei-patch to make this plugin to work

I mean necessaries of **this plugin**.

I'm going to test it to see if there's any error on the console.

**Comment by ghorsington** [comment]
While testing, make sure that it is **actually Maid Fiddler that causes the issue** and not just some other plugin/patcher.

Also consider changing the locale emulator (or disable it) when trying to use "Open translation folder", as it can affect the ability to launch other processes within the game itself.

**Comment by CaiMiao** [comment]
It's odd... It works again after I clean up the plugin and reinstall with Rei-only.
Sybaris-only would return unpatched (ID: 0) with/without rei-patched.

Anything I can confirm is that, before opening this issue and encounters the problem, I've tried to disable the plugin and results would load.

> As for the "Open translation folder" button, which locale emulator are you using (if any)?
>  In addition, does pressing the button cause any error messages?

It's just fine for the button, but it attemps to open unexisted folder at `GameRoot`/UnityInjector/..... , which is correct for ReiPatch-only users, instead of correct destination when you combines Sy. & Rei.

Just close this issue after the button fuction is fixed. When I encounter this problem again, I would reopen it.

**Comment by CaiMiao** [comment]
Adds: This is a rare problem which is even included in a FAQ guide in the community. I don't know why this problem occurs but it do exists. I've requested them to try to output a log to help solve this.
